###
###
GET localhost:8085/messages?uid=10012
x-token: eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEwMDEwfQ.O4NQJ3U8FGPzRB3IbMu6qmBwfQsS3eTLghRDDmWskHPtaaiUz_QEYz597XConGtjQXz8fL1T3XiA1FpCcQo5jQ

###