###

### Register
POST localhost:8085/register
Content-Type: application/json

{
  "name": "wf",
  "password": "123456"
}

### Login
POST localhost:8085/login
Content-Type: application/json

{
  "name": "wf",
  "password": "123456"
}

### info
GET localhost:8085/user/info
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjF9.ixhRZ7oxecHuRdEGjsETfBSWJP3hDECoQ_j4082hoF4


### getFriends
GET localhost:8085/user/getFriends
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjF9.ixhRZ7oxecHuRdEGjsETfBSWJP3hDECoQ_j4082hoF4

### searchFriend
GET localhost:8085/user/searchUser?name=wf
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjF9.ixhRZ7oxecHuRdEGjsETfBSWJP3hDECoQ_j4082hoF4

### deleteFriend
POST localhost:8085/user/deleteFriend
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjF9.ixhRZ7oxecHuRdEGjsETfBSWJP3hDECoQ_j4082hoF4

{
  "uid": 10012
}

### addFriend
POST localhost:8085/user/addFriend
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjF9.ixhRZ7oxecHuRdEGjsETfBSWJP3hDECoQ_j4082hoF4

{
  "uid": 10021
}