###

### Register
POST localhost:8085/register
Content-Type: application/json

{
  "name": "wf",
  "password": "123456"
}

### Login
POST localhost:8085/login
Content-Type: application/json

{
  "name": "wf",
  "password": "123456"
}

### info
GET localhost:8085/user/info
x-token: eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEwMDEwfQ.O4NQJ3U8FGPzRB3IbMu6qmBwfQsS3eTLghRDDmWskHPtaaiUz_QEYz597XConGtjQXz8fL1T3XiA1FpCcQo5jQ


### getFriends
GET localhost:8085/user/getFriends
x-token: eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEwMDEwfQ.O4NQJ3U8FGPzRB3IbMu6qmBwfQsS3eTLghRDDmWskHPtaaiUz_QEYz597XConGtjQXz8fL1T3XiA1FpCcQo5jQ

### searchFriend
GET localhost:8085/user/searchUser?name=wf
x-token: eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEwMDEwfQ.O4NQJ3U8FGPzRB3IbMu6qmBwfQsS3eTLghRDDmWskHPtaaiUz_QEYz597XConGtjQXz8fL1T3XiA1FpCcQo5jQ

### deleteFriend
POST localhost:8085/user/deleteFriend
Content-Type: application/json
x-token: eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEwMDEwfQ.O4NQJ3U8FGPzRB3IbMu6qmBwfQsS3eTLghRDDmWskHPtaaiUz_QEYz597XConGtjQXz8fL1T3XiA1FpCcQo5jQ

{
  "uid": 10012
}

### addFriend
POST localhost:8085/user/addFriend
Content-Type: application/json
x-token: eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEwMDEwfQ.O4NQJ3U8FGPzRB3IbMu6qmBwfQsS3eTLghRDDmWskHPtaaiUz_QEYz597XConGtjQXz8fL1T3XiA1FpCcQo5jQ

{
  "uid": 10021
}