[mysql]
host = "127.0.0.1"
port = 3306
username = "root"
password = "123456"
config = "charset=utf8mb4&parseTime=True&loc=Local"
dbName = "letter"
maxIdleConns = 10
maxOpenConns = 20

[log]
path = "logs/letter.log"
level = "debug"

[run]
mode = "release"
httpAddr = ":8085"
websocketAddr = ":8086"

[jwt]
signKey = "1u9bhw7LpmLjaJvF"

[file]
filePath = "assets/file"

[apollo]
appId = "letter"
ip = "http://localhost:8080"
secretKey = "0582299fcfd244f0bc24a2321addc872"
